### ISSUE TITLE
Logging-view container issues - Missing files

### ISSUE THREAD

**Issue by ndelrey** [openshift/logging-view-plugin#57]
Hi there

On Dec I was able to deploy Loki in an OCP 4.10 (s390x arch) and enabling the logging-view console without problems
Logging operator was 5.4.3.
Something happened during the X-mas holidays (not sure if someone upgraded the operator manually or it was due automatically) but the. logging-view plugin is not longer running (now it is running 5.5)

I can see logs like the following

`{"_ts":"2023-01-18T11:39:02.792504266Z","_level":"0","_component":"cluster-logging-operator","_message":"reconciling console","_error":{"msg":"ConsolePlugin.console.openshift.io \"logging-view-plugin\" is invalid: spec.proxy.service.name: Invalid value: \"\": spec.proxy.service.name in body should be at least 1 chars long"},"plugin":"console.openshift.io/v1alpha1/consoleplugins/logging-view-plugin"}`

and

`2023/01/18 12:09:04 [error] 7#0: *2 open() "/usr/share/nginx/html/locales/en/plugin_logging-view-plugin.json" failed (2: No such file or directory), client: 10.129.0.96, server: , request: "GET /locales/en/plugin_logging-view-plugin.json HTTP/1.1", host: "logging-view-plugin.openshift-logging.svc.cluster.local:9443", referrer: "https://console-openshift-console.apps.[redacted]/k8s/ns/openshift-logging/clusterserviceversions/cluster-logging.5.5.5/logging.openshift.io~v1~ClusterLogging/instance/yaml"`

It seems there are some missing files in the container and OCP Console can't connect with the service and it is not shown in the console

I've tried to downgrade completely the stack (back to 5.4.9), and I can see the same thing

For some reason the plugin_logging-view-plugin.json is not in the docker image. Indeed there is no /usr/share/nginx/html/locales folder 

Is anyone aware of that?

Thanks in advance

**Comment by abdinoorabdi** [comment]
Hi,

Has anyone had a chance to look at the above issue of missing files @ndelrey raised.



> Hi there
> 
> On Dec I was able to deploy Loki in an OCP 4.10 (s390x arch) and enabling the logging-view console without problems Logging operator was 5.4.3. Something happened during the X-mas holidays (not sure if someone upgraded the operator manually or it was due automatically) but the. logging-view plugin is not longer running (now it is running 5.5)
> 
> I can see logs like the following
> 
> `{"_ts":"2023-01-18T11:39:02.792504266Z","_level":"0","_component":"cluster-logging-operator","_message":"reconciling console","_error":{"msg":"ConsolePlugin.console.openshift.io \"logging-view-plugin\" is invalid: spec.proxy.service.name: Invalid value: \"\": spec.proxy.service.name in body should be at least 1 chars long"},"plugin":"console.openshift.io/v1alpha1/consoleplugins/logging-view-plugin"}`
> 
> and
> 
> `2023/01/18 12:09:04 [error] 7#0: *2 open() "/usr/share/nginx/html/locales/en/plugin_logging-view-plugin.json" failed (2: No such file or directory), client: 10.129.0.96, server: , request: "GET /locales/en/plugin_logging-view-plugin.json HTTP/1.1", host: "logging-view-plugin.openshift-logging.svc.cluster.local:9443", referrer: "https://console-openshift-console.apps.[redacted]/k8s/ns/openshift-logging/clusterserviceversions/cluster-logging.5.5.5/logging.openshift.io~v1~ClusterLogging/instance/yaml"`
> 
> It seems there are some missing files in the container and OCP Console can't connect with the service and it is not shown in the console
> 
> I've tried to downgrade completely the stack (back to 5.4.9), and I can see the same thing
> 
> For some reason the plugin_logging-view-plugin.json is not in the docker image. Indeed there is no /usr/share/nginx/html/locales folder
> 
> Is anyone aware of that?
> 
> Thanks in advance

**Comment by ndelrey** [comment]
Hey @jgbernalp  , thanks for your help

Yes, I've tried to enable/disable the plugin several times and no way

Related to the translation files... for some reason the service is not doing this "fallback" or at least it tries to load some files from /locales/en ...

Do you know when it is planned the new release?

**Comment by ndelrey** [comment]
@jgbernalp 
any news on this issue?
Is it fixed on Cluster-Logging-Operator 5.6?

**Comment by jgbernalp** [comment]
@ndelrey The PR adding the translations was added https://github.com/openshift/logging-view-plugin/pull/84 and planned to land in 5.7. 

OCP 4.10 tries to load the translation files even if the plugin doesn't support it, this is a known [issue](https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md#:~:text=Prior%20to%204.11%20release%2C%20localization%20resources%20are%20being%20loaded%20by%20default.%20In%20case%20these%20resources%20are%20not%20present%20in%20the%20dynamic%20plugin%2C%20the%20initial%20console%20load%20will%20be%20slowed%20down.%20For%20more%20info%20check%20BZ%232015654) that was addressed in 4.11

**Comment by ndelrey** [comment]
Thanks a lot for the feedback @jgbernalp 
@abdinoorabdi upgrading may solve the issue
